### ISSUE TITLE
Add a README

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/HacktoberFest-Responsive-Portfolio#4]
Add a nice and easy to read README for the contributors.☺

**Comment by SamikshaSankar** [comment]
Please assign @Sanchitbajaj02

**Comment by Sanchitbajaj02** [comment]
Go ahead @SamikshaSankar

**Comment by abheer18** [comment]
please assign @Sanchitbajaj02 !!

**Comment by Sanchitbajaj02** [comment]
Go ahead @abheer18
